export const flowers = [
    {
        "id": 3782,
        "name": "Say You Do",
        "slug": "bo-hoa-cat-tuong-say-you-do",
        "current_stock": 100,
        "variant_id": 8846,
        "variant": "C\u01a1 B\u1ea3n",
        "sku": "FL0000972",
        "prioritization": 1,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/250_CJdqphTj2inAgamCk3IAqUMuz.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "849000.00",
        "purchase_price": "429000.00",
        "vendor_id": 1,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 36,
        "name": "Dream Of You",
        "slug": "bo-hoa-dream-of-you",
        "current_stock": 200,
        "variant_id": 1443,
        "variant": "default",
        "sku": "FL000309",
        "prioritization": 2,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/350_5WxbtQDZtB10W4qLyp53t5E4X.jpg",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "399000.00",
        "purchase_price": "279000.00",
        "vendor_id": 1,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 3821,
        "name": "L\u1eddi Y\u00eau Ng\u00e2y D\u1ea1i",
        "slug": "bo-hoa-hong-loi-yeu-ngay-dai",
        "current_stock": 100,
        "variant_id": 8909,
        "variant": "C\u01a1 B\u1ea3n",
        "sku": "FL0000985",
        "prioritization": 3,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/250_lf1wORnI7AuuD2hUgNjAgpnKF.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "299000.00",
        "purchase_price": "199000.00",
        "vendor_id": 1,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 3813,
        "name": "N\u1ee5 C\u01b0\u1eddi Em",
        "slug": "bo-hoa-hong-nu-cuoi-em",
        "current_stock": 100,
        "variant_id": 8896,
        "variant": "C\u01a1 B\u1ea3n",
        "sku": "FL0000980",
        "prioritization": 4,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/250_0bACbti4VfBCQUzVM0fTZ081W.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "549000.00",
        "purchase_price": "299000.00",
        "vendor_id": 1,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 1392,
        "name": "Ariana",
        "slug": "bo-hoa-tulip-ariana",
        "current_stock": 10,
        "variant_id": 2711,
        "variant": "default",
        "sku": "FL0000590",
        "prioritization": 5,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/350_tp8pYcd4CPbOGkMECGu6CPPWZ.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "1249000.00",
        "purchase_price": "749000.00",
        "vendor_id": 1,
        "advance_days": "2023-06-18",
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 236,
        "name": "True Love (99 B\u00f4ng)",
        "slug": "bo-hoa-hong-true-love",
        "current_stock": 2000,
        "variant_id": 1632,
        "variant": "default",
        "sku": "FL000070",
        "prioritization": 6,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/350_5InO1UN8uQT7QhHdg09fG9S5D.jpg",
        "ratings": "5.0",
        "reviews": 4,
        "unit_price": "1499000.00",
        "purchase_price": "1149000.00",
        "vendor_id": 68,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 3709,
        "name": "Ly S\u1ee9 Thi\u1ebft K\u1ebf Sinh Nh\u1eadt",
        "slug": "ly-su-thiet-ke-sinh-nhat",
        "current_stock": 10,
        "variant_id": 8690,
        "variant": "M\u1eabu 1",
        "sku": "NF000861-1",
        "prioritization": 7,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/250_pOV4CINc8qbk9M7yG1Q00TZSG.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "199000.00",
        "purchase_price": "179000.00",
        "vendor_id": 1,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 3583,
        "name": "Set Qu\u00e0 N\u1ebfn th\u01a1m T\u00ecnh Y\u00eau Thu\u1ea7n Khi\u1ebft",
        "slug": "set-qua-nen-thom-tinh-yeu-thuan-khiet",
        "current_stock": 99,
        "variant_id": 8446,
        "variant": "Courage",
        "sku": "NF000755_C",
        "prioritization": 8,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/350_Ay4haUbyVGS05hGszglu7N2it.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "429000.00",
        "purchase_price": "299000.00",
        "vendor_id": 70,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 1400,
        "name": "Sweet As You",
        "slug": "banh-kem-hoa-sweet-as-you",
        "current_stock": 10,
        "variant_id": 2719,
        "variant": "default",
        "sku": "FL0000595",
        "prioritization": 9,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/350_NfkO2x4gl9oR4p4sozHdmL86M.jpg",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "1099000.00",
        "purchase_price": "799000.00",
        "vendor_id": 92,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 3778,
        "name": "H\u1ed9p Qu\u00e0 Th\u01a1m Th\u1ea3o",
        "slug": "hop-qua-thom-thao",
        "current_stock": 100,
        "variant_id": 8838,
        "variant": "B\u00ecnh Xanh",
        "sku": "NF000891",
        "prioritization": 10,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/250_1cFt71hx2m2rZ9rGQ84nV5pSk.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "429000.00",
        "purchase_price": "329000.00",
        "vendor_id": 105,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 3719,
        "name": "B\u00e1nh Kem Em B\u00e9",
        "slug": "banh-kem-em-be",
        "current_stock": 999,
        "variant_id": 8709,
        "variant": "B\u01b0\u1edbm Xinh",
        "sku": "NF000863_B",
        "prioritization": 11,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/250_avd8irGlpxBs3vuFzVC2OniT7.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "559000.00",
        "purchase_price": "429000.00",
        "vendor_id": 74,
        "advance_days": "2023-06-18",
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    },
    {
        "id": 3587,
        "name": "H\u1ed9p Qu\u00e0 Hoa V\u00e0 Socola N\u1ed3ng Th\u1eafm",
        "slug": "hop-qua-hoa-va-socola-nong-tham",
        "current_stock": 999,
        "variant_id": 8454,
        "variant": "C\u01a1 b\u1ea3n",
        "sku": "NF000760",
        "prioritization": 12,
        "thumbnail": "https:\/\/assets.flowerstore.ph\/public\/tenantVN\/app\/assets\/images\/product\/250_PbxAPZbO8A1TIAFp2xzmtzFSs.webp",
        "ratings": 0,
        "reviews": 0,
        "unit_price": "649000.00",
        "purchase_price": "499000.00",
        "vendor_id": 93,
        "advance_days": null,
        "collection_id": 11,
        "collection_name": "Birthday Gifts",
        "campaign_product": false
    }
]